FROM postgres:16-alpine

COPY ./docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

RUN chmod +x /docker-entrypoint-initdb.d/*.sh 2>/dev/null || true

RUN mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql/data

USER postgres

EXPOSE 5432

CMD ["postgres"]
